remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Flow's PSU Tier List]
description: [A PSU Tier List made by Flow, with no affiliate links for everyone to enjoy.]
